# Generated by Django 5.2.6 on 2026-10-03 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("orden", models.PositiveIntegerField(verbose_name="orden")),
                ("etiqueta", models.CharField(max_length=20, verbose_name="etiqueta (codigo G)")),
                ("parametro", models.FloatField(blank=True, null=True, verbose_name="parametro")),
                (
                    "repeticiones",
                    models.PositiveIntegerField(default=1, verbose_name="repeticiones"),
                ),
                (
                    "tiempo_de_pulso",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cero para instrucciones que no disparan el laser.",
                        verbose_name="tiempo de pulso [ms]",
                    ),
                ),
            ],
            options={
                "verbose_name": "paso",
                "verbose_name_plural": "pasos",
                "ordering": ["programa", "orden"],
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONSTANTE", "Constante"),
                            ("LINEAL", "Lineal"),
                            ("EXPONENCIAL", "Exponencial"),
                        ],
                        default="CONSTANTE",
                        max_length=15,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "periodo_base",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                        verbose_name="periodo base [um]",
                    ),
                ),
                (
                    "incremento",
                    models.FloatField(
                        blank=True,
                        help_text="Solo para el perfil LINEAL.",
                        null=True,
                        verbose_name="incremento [um]",
                    ),
                ),
                (
                    "factor",
                    models.FloatField(
                        blank=True,
                        help_text="Solo para el perfil EXPONENCIAL.",
                        null=True,
                        verbose_name="factor",
                    ),
                ),
            ],
            options={
                "verbose_name": "periodo",
                "verbose_name_plural": "periodos",
            },
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True, verbose_name="codigo")),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripcion")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="version")),
                (
                    "tipo_red",
                    models.CharField(
                        choices=[("LPG", "LPG"), ("HLPG", "HLPG"), ("pHLPG", "pHLPG")],
                        max_length=10,
                        verbose_name="tipo de red",
                    ),
                ),
                ("potencia_objetivo", models.FloatField(verbose_name="potencia objetivo [W]")),
                (
                    "criterio_fin",
                    models.CharField(
                        choices=[
                            ("CANT_MARCAS", "Cantidad de marcas"),
                            ("LONGITUD", "Longitud"),
                            ("TIEMPO", "Tiempo"),
                            ("ATENUACION_OBJETIVO", "Atenuacion objetivo"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=25,
                        verbose_name="criterio de fin",
                    ),
                ),
                (
                    "valor_criterio_fin",
                    models.FloatField(
                        blank=True, null=True, verbose_name="valor del criterio de fin"
                    ),
                ),
                ("validado", models.BooleanField(default=False, verbose_name="validado")),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True, verbose_name="creado en")),
            ],
            options={
                "verbose_name": "programa",
                "verbose_name_plural": "programas",
                "ordering": ["codigo", "-version"],
            },
        ),
    ]
