# Generated by Django 5.2.6 on 2026-10-03 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="programa",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creado por",
            ),
        ),
        migrations.AddField(
            model_name="programa",
            name="periodo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programa",
                to="programas.periodo",
                verbose_name="periodo",
            ),
        ),
        migrations.AddField(
            model_name="paso",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pasos",
                to="programas.programa",
                verbose_name="programa",
            ),
        ),
        migrations.AddConstraint(
            model_name="paso",
            constraint=models.UniqueConstraint(
                fields=("programa", "orden"), name="paso_programa_orden_unico"
            ),
        ),
    ]
