# Generated by Django 5.2.6 on 2026-10-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programa",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
        ),
    ]
