# Generated by Django 5.2.6 on 2026-10-03 23:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True, verbose_name="numero")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripcion")),
                ("fecha_inicio", models.DateField(verbose_name="fecha de inicio")),
            ],
            options={
                "verbose_name": "lote",
                "verbose_name_plural": "lotes",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="Procedimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=120, verbose_name="titulo")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripcion")),
                ("version", models.CharField(default="1.0", max_length=20, verbose_name="version")),
                (
                    "span",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="span [nm]",
                    ),
                ),
                (
                    "resolucion",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                        verbose_name="resolucion [nm]",
                    ),
                ),
                (
                    "sensibilidad",
                    models.CharField(blank=True, max_length=40, verbose_name="sensibilidad"),
                ),
                (
                    "escala_vertical",
                    models.FloatField(
                        blank=True, null=True, verbose_name="escala vertical [dB/div]"
                    ),
                ),
                (
                    "corriente_sld",
                    models.FloatField(blank=True, null=True, verbose_name="corriente del SLD [mA]"),
                ),
            ],
            options={
                "verbose_name": "procedimiento de medicion",
                "verbose_name_plural": "procedimientos de medicion",
                "ordering": ["titulo", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("titulo", "version"), name="procedimiento_titulo_version_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Red",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="numero")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LPG", "LPG"), ("HLPG", "HLPG"), ("pHLPG", "pHLPG")],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("VIABLE", "Viable"), ("INVIABLE", "Inviable"), ("ROTA", "Rota")],
                        default="VIABLE",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("fecha_fabricacion", models.DateField(verbose_name="fecha de fabricacion")),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redes",
                        to="fabricacion.lote",
                        verbose_name="lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "red",
                "verbose_name_plural": "redes",
                "ordering": ["-lote__numero", "numero"],
            },
        ),
        migrations.CreateModel(
            name="PicoDeAtenuacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "longitud_onda",
                    models.FloatField(db_index=True, verbose_name="longitud de onda [nm]"),
                ),
                ("transmitancia", models.FloatField(verbose_name="transmitancia [dB]")),
                ("principal", models.BooleanField(default=False, verbose_name="es la principal")),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picos",
                        to="fabricacion.red",
                        verbose_name="red",
                    ),
                ),
            ],
            options={
                "verbose_name": "pico de atenuacion",
                "verbose_name_plural": "picos de atenuacion",
                "ordering": ["red", "longitud_onda"],
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="numero")),
                ("posicion", models.FloatField(verbose_name="posicion [um]")),
                ("cant_pulsos", models.PositiveIntegerField(verbose_name="cantidad de pulsos")),
                ("ciclo_trabajo", models.FloatField(verbose_name="ciclo de trabajo [%]")),
                (
                    "tiempo_de_pulso",
                    models.PositiveIntegerField(verbose_name="tiempo de pulso [ms]"),
                ),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marcas",
                        to="fabricacion.red",
                        verbose_name="red",
                    ),
                ),
            ],
            options={
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
                "ordering": ["red", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Espectro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha_captura", models.DateTimeField(verbose_name="fecha de captura")),
                (
                    "longitud_onda_inicial",
                    models.FloatField(verbose_name="longitud de onda inicial [nm]"),
                ),
                (
                    "transmitancias",
                    models.JSONField(default=list, verbose_name="transmitancias [dB]"),
                ),
                (
                    "procedimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="espectros",
                        to="fabricacion.procedimiento",
                        verbose_name="procedimiento",
                    ),
                ),
                (
                    "red",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espectro",
                        to="fabricacion.red",
                        verbose_name="red",
                    ),
                ),
            ],
            options={
                "verbose_name": "espectro",
                "verbose_name_plural": "espectros",
                "ordering": ["-fecha_captura"],
            },
        ),
        migrations.AddConstraint(
            model_name="red",
            constraint=models.UniqueConstraint(
                fields=("lote", "numero"), name="red_lote_numero_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="picodeatenuacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal", True)),
                fields=("red",),
                name="una_sola_resonancia_principal_por_red",
            ),
        ),
        migrations.AddConstraint(
            model_name="marca",
            constraint=models.UniqueConstraint(
                fields=("red", "numero"), name="marca_red_numero_unica"
            ),
        ),
    ]
