# Generated by Django 5.2.6 on 2026-10-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fabricacion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="picodeatenuacion",
            name="una_sola_resonancia_principal_por_red",
        ),
        migrations.AddField(
            model_name="picodeatenuacion",
            name="_red_principal",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(principal=True, then=models.F("red")), default=models.Value(None)
                ),
                output_field=models.BigIntegerField(null=True),
                verbose_name="indice de unicidad de la principal",
            ),
        ),
        migrations.AddConstraint(
            model_name="picodeatenuacion",
            constraint=models.UniqueConstraint(
                fields=("_red_principal",), name="una_sola_resonancia_principal_por_red"
            ),
        ),
    ]
