# Generated by Django 5.2.6 on 2026-10-03 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operacion", "0001_initial"),
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("numero", models.PositiveIntegerField(verbose_name="numero")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("TIEMPO", "Por tiempo"), ("MARCA", "Por marca")],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha y hora"),
                ),
                (
                    "estado_sistema",
                    models.CharField(
                        choices=[
                            ("REPOSO", "En reposo"),
                            ("PREPARANDO", "Preparando"),
                            ("LISTO", "Listo para grabar"),
                            ("GRABANDO", "Grabando"),
                            ("EMERGENCIA", "Emergencia"),
                        ],
                        max_length=15,
                        verbose_name="estado del sistema",
                    ),
                ),
                ("valores", models.JSONField(default=dict, verbose_name="valores medidos")),
                (
                    "paso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkpoints",
                        to="programas.paso",
                        verbose_name="paso",
                    ),
                ),
            ],
            options={
                "verbose_name": "checkpoint",
                "verbose_name_plural": "checkpoints",
                "ordering": ["registro", "numero"],
            },
        ),
        migrations.CreateModel(
            name="RegistroDeFabricacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=40, unique=True, verbose_name="codigo")),
                (
                    "modo",
                    models.CharField(
                        choices=[("REAL", "Real"), ("PRUEBA", "Prueba")],
                        default="REAL",
                        max_length=10,
                        verbose_name="modo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_CURSO", "En curso"),
                            ("COMPLETADO", "Completado"),
                            ("INTERRUMPIDO", "Interrumpido"),
                            ("ABORTADO", "Abortado"),
                        ],
                        default="EN_CURSO",
                        max_length=15,
                        verbose_name="estado",
                    ),
                ),
                (
                    "inicio",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="inicio"),
                ),
                ("fin", models.DateTimeField(blank=True, null=True, verbose_name="fin")),
                (
                    "calibracion_arco",
                    models.BooleanField(default=False, verbose_name="calibracion de arco"),
                ),
                ("observaciones", models.TextField(blank=True, verbose_name="observaciones")),
                (
                    "configuracion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="operacion.configuracion",
                        verbose_name="configuracion vigente",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de fabricacion",
                "verbose_name_plural": "registros de fabricacion",
                "ordering": ["-inicio"],
            },
        ),
    ]
