# Generated by Django 5.2.6 on 2026-10-03 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fabricacion", "0001_initial"),
        ("programas", "0002_initial"),
        ("trazabilidad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodefabricacion",
            name="operadores",
            field=models.ManyToManyField(
                related_name="registros", to=settings.AUTH_USER_MODEL, verbose_name="operadores"
            ),
        ),
        migrations.AddField(
            model_name="registrodefabricacion",
            name="procedimiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros",
                to="fabricacion.procedimiento",
                verbose_name="procedimiento de medicion",
            ),
        ),
        migrations.AddField(
            model_name="registrodefabricacion",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros",
                to="programas.programa",
                verbose_name="programa",
            ),
        ),
        migrations.AddField(
            model_name="registrodefabricacion",
            name="red",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros",
                to="fabricacion.red",
                verbose_name="red producida",
            ),
        ),
        migrations.AddField(
            model_name="checkpoint",
            name="registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="trazabilidad.registrodefabricacion",
                verbose_name="registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkpoint",
            constraint=models.UniqueConstraint(
                fields=("registro", "numero"), name="checkpoint_registro_numero_unico"
            ),
        ),
    ]
