# Generated by Django 5.2.6 on 2026-10-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="fecha y hora"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="descripcion")),
                ("sugerencia", models.TextField(blank=True, verbose_name="sugerencia")),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("INFO", "Informativa"),
                            ("ADVERTENCIA", "Advertencia"),
                            ("CRITICA", "Critica"),
                        ],
                        max_length=12,
                        verbose_name="severidad",
                    ),
                ),
                ("valor_medido", models.FloatField(verbose_name="valor medido")),
                (
                    "reconocida",
                    models.BooleanField(db_index=True, default=False, verbose_name="reconocida"),
                ),
                (
                    "reconocida_en",
                    models.DateTimeField(blank=True, null=True, verbose_name="reconocida en"),
                ),
            ],
            options={
                "verbose_name": "alerta",
                "verbose_name_plural": "alertas",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                ("descripcion", models.TextField(blank=True, verbose_name="descripcion")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="version")),
                ("activa", models.BooleanField(default=False, verbose_name="activa")),
                ("creada_en", models.DateTimeField(auto_now_add=True, verbose_name="creada en")),
            ],
            options={
                "verbose_name": "configuracion",
                "verbose_name_plural": "configuraciones",
                "ordering": ["nombre", "-version"],
            },
        ),
        migrations.CreateModel(
            name="EventoEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="fecha y hora"
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("BOTON_FISICO", "Boton fisico"),
                            ("UMBRAL", "Umbral excedido"),
                            ("OPERADOR", "Operador"),
                        ],
                        max_length=15,
                        verbose_name="origen",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, verbose_name="descripcion")),
                (
                    "tiempo_respuesta_ms",
                    models.PositiveIntegerField(
                        help_text="Evidencia de RNF001: el presupuesto son 500 ms.",
                        verbose_name="tiempo de respuesta [ms]",
                    ),
                ),
                (
                    "rearmado_en",
                    models.DateTimeField(blank=True, null=True, verbose_name="rearmado en"),
                ),
            ],
            options={
                "verbose_name": "evento de emergencia",
                "verbose_name_plural": "eventos de emergencia",
                "ordering": ["-fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="Umbral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "variable",
                    models.CharField(
                        choices=[
                            ("TEMPERATURA_AGUA", "Temperatura del agua [C]"),
                            ("CAUDAL_REFRIGERANTE", "Caudal de refrigerante [L/min]"),
                            ("POTENCIA_LASER", "Potencia del laser [W]"),
                            ("TENSION_AT", "Tension de alta tension [kV]"),
                            ("CORRIENTE_AT", "Corriente de alta tension [mA]"),
                            ("POSICION_MOTOR", "Posicion del motor [mm]"),
                            ("TEMPERATURA_AMBIENTE", "Temperatura ambiente [C]"),
                        ],
                        max_length=25,
                        verbose_name="variable",
                    ),
                ),
                ("valor_min", models.FloatField(verbose_name="valor minimo")),
                ("valor_max", models.FloatField(verbose_name="valor maximo")),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("INFO", "Informativa"),
                            ("ADVERTENCIA", "Advertencia"),
                            ("CRITICA", "Critica"),
                        ],
                        default="ADVERTENCIA",
                        max_length=12,
                        verbose_name="severidad",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("ALERTA", "Solo alertar"),
                            ("BLOQUEAR_COMANDO", "Bloquear comandos"),
                            ("PARADA_EMERGENCIA", "Parada de emergencia"),
                        ],
                        default="ALERTA",
                        max_length=20,
                        verbose_name="accion",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "umbral",
                "verbose_name_plural": "umbrales",
                "ordering": ["configuracion", "variable"],
            },
        ),
    ]
