# Generated by Django 5.2.6 on 2026-10-03 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operacion", "0001_initial"),
        ("trazabilidad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="reconocida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas_reconocidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reconocida por",
            ),
        ),
        migrations.AddField(
            model_name="configuracion",
            name="definida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuraciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="definida por",
            ),
        ),
        migrations.AddField(
            model_name="eventoemergencia",
            name="rearmado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergencias_rearmadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="rearmado por",
            ),
        ),
        migrations.AddField(
            model_name="eventoemergencia",
            name="registro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emergencias",
                to="trazabilidad.registrodefabricacion",
                verbose_name="registro interrumpido",
            ),
        ),
        migrations.AddField(
            model_name="umbral",
            name="configuracion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="umbrales",
                to="operacion.configuracion",
                verbose_name="configuracion",
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="umbral",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas",
                to="operacion.umbral",
                verbose_name="umbral",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracion",
            constraint=models.UniqueConstraint(
                fields=("nombre", "version"), name="configuracion_nombre_version_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("activa", True)),
                fields=("activa",),
                name="una_sola_configuracion_activa",
            ),
        ),
        migrations.AddConstraint(
            model_name="umbral",
            constraint=models.UniqueConstraint(
                fields=("configuracion", "variable"), name="un_umbral_por_variable_y_configuracion"
            ),
        ),
        migrations.AddConstraint(
            model_name="umbral",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_min__lt", models.F("valor_max"))),
                name="umbral_min_menor_que_max",
            ),
        ),
    ]
