# Generated by Django 5.2.6 on 2026-10-03 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operacion", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="configuracion",
            name="una_sola_configuracion_activa",
        ),
        migrations.AddField(
            model_name="configuracion",
            name="_activa_unica",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(activa=True, then=models.Value(1)), default=models.Value(None)
                ),
                output_field=models.IntegerField(null=True),
                verbose_name="indice de unicidad de la vigente",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracion",
            constraint=models.UniqueConstraint(
                fields=("_activa_unica",), name="una_sola_configuracion_activa"
            ),
        ),
    ]
